import type { GameEvent } from "./types";

export const EVENTS: GameEvent[] = [
  {
    id: "tucuman_1816",
    speaker: "Diputado de Tucumán",
    role: "Congreso",
    title: "El Congreso espera tu firma",
    text: "Julio de 1816. En una sala de cal y vela se discute cortar el último hilo con Fernando VII. Declarar la independencia es irreversible: España no perdona, y el Alto Perú aún arde.",
    art: "/art/independence.jpg",
    kind: "historia",
    eras: ["independencia"],
    minYear: 1816,
    maxYear: 1820,
    once: true,
    priority: 100,
    yearsAdvance: 1,
    left: {
      label: "Declarar la Independencia",
      narrative: "Nace la Nación. Sube el ánimo y el peso exterior; el tesoro se resiente.",
      effects: { people: 16, prestige: 12, forces: 8, economy: -6, image: 10 },
      flags: ["independent"],
      ideology: { rights: 1 },
      log: "Se declara la Independencia en Tucumán.",
    },
    right: {
      label: "Esperar un protector europeo",
      narrative: "Una corona tutelar puede traer crédito, pero arriesga el cierre del relato patriótico.",
      effects: { prestige: -10, people: -12, forces: -6, economy: 4, image: -8 },
      flags: ["hesitant_1816"],
      followUp: "tucuman_rebuke",
      log: "El Congreso duda; Europa no ofrece corona.",
    },
  },
  {
    id: "tucuman_rebuke",
    speaker: "Secretario del Congreso",
    role: "Gabinete",
    title: "Nadie viene a salvarnos",
    text: "Londres sonríe y no mueve un barco. Río de Janeiro pide precios. El pueblo ya canta libertad en las pulperías.",
    art: "/art/independence.jpg",
    kind: "historia",
    eras: ["independencia"],
    once: true,
    priority: 100,
    requireFlags: ["hesitant_1816"],
    yearsAdvance: 1,
    left: {
      label: "Firmar de una vez",
      narrative: "Independencia tardía, pero firme. Recupera algo de plaza y de mapa.",
      effects: { people: 10, prestige: 8, forces: 6, image: 6 },
      flags: ["independent"],
      log: "Independencia tardía, pero firme.",
    },
    right: {
      label: "Seguir negociando",
      narrative: "El Congreso se parte. El relato nace sucio.",
      effects: { prestige: -8, people: -10, forces: -8, corruption: 6, image: -6 },
      flags: ["independent"],
      log: "Se declara igual, entre rumores de venta.",
    },
  },
  {
    id: "cruce_andes",
    speaker: "General de los Andes",
    role: "Ejército",
    title: "Un ejército sobre la cordillera",
    text: "Propone pasar a Chile con mulares, cañones desarmados y el invierno como cómplice. Es una apuesta ruinosa o una gesta.",
    art: "/art/andes.jpg",
    kind: "historia",
    eras: ["independencia"],
    minYear: 1816,
    maxYear: 1824,
    once: true,
    priority: 88,
    requireFlags: ["independent"],
    yearsAdvance: 2,
    left: {
      label: "Cruzar los Andes",
      narrative: "Gesta militar: sube lealtad y prestigio, sangra el tesoro.",
      effects: { forces: 14, prestige: 16, economy: -8, people: 8, image: 8 },
      flags: ["andes_crossing"],
      ideology: { militar: 1 },
      log: "El Ejército de los Andes cruza la cordillera.",
    },
    right: {
      label: "Fortificar el litoral",
      narrative: "Prioriza aduanas y milicias locales; Chile espera y el mapa se achica.",
      effects: { forces: 4, economy: 6, prestige: -10, people: -4, image: -6 },
      log: "Se prioriza el litoral; Chile espera.",
    },
  },
  {
    id: "triple_alianza",
    speaker: "Ministro de Guerra",
    role: "Gabinete",
    title: "Guerra de la Triple Alianza",
    text: "Paraguay se adelanta sobre Corrientes. Brasil y Uruguay ya firmaron. Entrar es una carnicería de años; quedarse fuera es dejar el Litoral al fuego y a Pedro II.",
    art: "/art/alliance.jpg",
    kind: "historia",
    eras: ["independencia"],
    minYear: 1864,
    maxYear: 1872,
    once: true,
    priority: 92,
    yearsAdvance: 4,
    left: {
      label: "Entrar en la Triple Alianza",
      narrative: "Alinea al país con Brasil e imperio. Sangra economía y ánimo; el ejército se prueba.",
      effects: { forces: 8, prestige: 6, economy: -16, people: -10, corruption: 6, image: 4 },
      flags: ["triple_alliance"],
      followUp: "triple_costo",
      ideology: { militar: 1, washington: 0, brics: 0 },
      log: "Argentina entra en la guerra contra Paraguay.",
    },
    right: {
      label: "Negociar una paz separada",
      narrative: "Evita la carnicería, pero arriesga quedar como socio menor del Imperio.",
      effects: { economy: 6, prestige: -12, forces: -8, people: 4, image: -8 },
      flags: ["avoided_paraguay"],
      log: "Se evade la Triple Alianza; Brasil avanza solo.",
    },
  },
  {
    id: "triple_costo",
    speaker: "Cirujano de campaña",
    role: "Frente",
    title: "El costo de Humaitá",
    text: "Fiebre, barro y listas de muertos que no entran en el parte. El interior dice que es una guerra porteña.",
    art: "/art/alliance.jpg",
    kind: "historia",
    eras: ["independencia"],
    once: true,
    priority: 100,
    requireFlags: ["triple_alliance"],
    yearsAdvance: 3,
    left: {
      label: "Llevar la guerra hasta Asunción",
      narrative: "Victoria cara: prestigio de potencia regional, pueblo exhausto.",
      effects: { forces: -8, prestige: 10, economy: -12, people: -8, image: 6 },
      flags: ["won_paraguay"],
      log: "La guerra termina en Asunción, carísima.",
    },
    right: {
      label: "Pedir armisticio ya",
      narrative: "Salva vidas y enoja a los aliados. La herida queda abierta.",
      effects: { people: 8, forces: 4, prestige: -10, economy: -4, image: -6 },
      flags: ["won_paraguay"],
      ideology: { rights: 1 },
      log: "Armisticio prematuro; la herida queda abierta.",
    },
  },
  {
    id: "inmigracion_europea",
    speaker: "Director de Inmigración",
    role: "Puerto",
    title: "Inmigración europea masiva",
    text: "Vapores italianos y españoles vomitan familias en la Dársena. Gobernar es poblar, dicen. También es conventillo, huelga y una lengua nueva en el convento.",
    art: "/art/immigration.jpg",
    kind: "historia",
    eras: ["independencia"],
    minYear: 1876,
    maxYear: 1914,
    once: true,
    priority: 84,
    yearsAdvance: 6,
    left: {
      label: "Abrir el puerto de par en par",
      narrative: "Multiplica brazos y prestigio de granero del mundo; tensiona el orden.",
      effects: { economy: 14, prestige: 10, people: 6, forces: -4, corruption: 4, image: 8 },
      flags: ["euro_immigration"],
      souvenirs: ["vino_italia"],
      ideology: { market: 1 },
      log: "Oleada europea: el país se multiplica.",
    },
    right: {
      label: "Cuotas y aduana selectiva",
      narrative: "Calma a las ligas patrióticas; el campo espera brazos que no llegan.",
      effects: { forces: 6, people: -4, economy: -8, prestige: -6, image: -4 },
      log: "Inmigración restringida; el campo espera brazos.",
    },
  },
  {
    id: "inmigracion_regional",
    speaker: "Gobernador del norte",
    role: "Interior",
    title: "Braceros del norte",
    text: "De Bolivia, Paraguay y el altiplano llegan brazos para el azúcar y el tanino. No salen en los afiches de Europa, pero sostienen la zafra.",
    art: "/art/jujuy.jpg",
    kind: "provincia",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1910,
    once: true,
    priority: 55,
    yearsAdvance: 2,
    left: {
      label: "Regularizar y sindicalizar",
      narrative: "Reconoce la inmigración regional: ánimo en el norte, roce con las aduanas.",
      effects: { people: 10, economy: 5, corruption: 3, prestige: 3, image: 3 },
      flags: ["regional_migration"],
      ideology: { rights: 1 },
      log: "Se reconoce la inmigración regional.",
    },
    right: {
      label: "Frontera dura y razzias",
      narrative: "Gendarmería en la puna: sube el orden, cae el norte.",
      effects: { forces: 8, people: -10, economy: -5, prestige: -4, image: -4 },
      ideology: { militar: 1 },
      log: "Razzias en villas; el norte se enoja.",
    },
  },
  {
    id: "antartida",
    speaker: "Capitán de fragata",
    role: "Armada",
    title: "Soberanía antártica",
    text: "Orcadas ya es argentina, pero Chile y Londres dibujan el mismo triángulo. Una base más, un sello más, un invierno más. El hielo no se discute si no estás ahí.",
    art: "/art/antarctica.jpg",
    kind: "historia",
    eras: ["independencia", "dictadura", "noventa"],
    minYear: 1904,
    once: true,
    priority: 60,
    yearsAdvance: 2,
    left: {
      label: "Instalar bases y reclamar",
      narrative: "Presencia permanente: prestigio polar y un gasto que no se ve en la plaza.",
      effects: { prestige: 12, forces: 6, economy: -9, people: 5, image: 8 },
      flags: ["antarctica"],
      log: "Se refuerza la presencia antártica.",
    },
    right: {
      label: "Dejarlo a las sociedades geográficas",
      narrative: "Ahorra tesoro; el mapa queda en manos ajenas.",
      effects: { economy: 4, prestige: -10, people: -4, image: -8 },
      log: "La Antártida queda en el mapa ajeno.",
    },
  },
  {
    id: "wwi",
    speaker: "Embajador británico",
    role: "Entente",
    title: "La Gran Guerra",
    text: "Londres quiere granos y carne; Berlín, una radio en Patagonia. La Sociedad Rural pide neutralidad lucrativa. Un barco torpedeado puede arrastrarnos.",
    art: "/art/worldwar.jpg",
    kind: "historia",
    eras: ["independencia"],
    minYear: 1914,
    maxYear: 1919,
    once: true,
    priority: 90,
    yearsAdvance: 4,
    left: {
      label: "Neutralidad estricta",
      narrative: "El trigo vale oro. Se gana caja y se pierde una silla en Versalles.",
      effects: { economy: 12, prestige: -4, forces: 4, people: 4, image: -4 },
      flags: ["wwi_neutral"],
      ideology: { market: 1 },
      log: "Neutralidad en la Gran Guerra: el trigo vale oro.",
    },
    right: {
      label: "Alinearse con los Aliados",
      narrative: "Abre crédito y diplomacia aliada; arriesga el mercado alemán y algún motín.",
      effects: { prestige: 12, forces: 6, economy: -8, people: -5, image: 10 },
      flags: ["wwi_allies", "un_active"],
      ideology: { washington: 1 },
      log: "Ruptura con los Imperios Centrales.",
    },
  },
  {
    id: "wwii",
    speaker: "Agregado de Washington",
    role: "Embajada",
    title: "La segunda guerra",
    text: "Brasil ya declaró. Estados Unidos amenaza con armas y créditos. El GOU murmura que el Eje es el orden. El pueblo come asado y escucha la BBC.",
    art: "/art/worldwar.jpg",
    kind: "historia",
    eras: ["independencia"],
    minYear: 1939,
    maxYear: 1945,
    once: true,
    priority: 90,
    yearsAdvance: 4,
    left: {
      label: "Mantener la neutralidad",
      narrative: "Caja corta plazo; cierra puertas en el mundo de posguerra.",
      effects: { economy: 8, prestige: -12, forces: 6, people: 4, image: -12, inflation: 4 },
      flags: ["wwii_neutral"],
      marketClosed: true,
      log: "Neutralidad larga en la Segunda Guerra.",
    },
    right: {
      label: "Romper con el Eje",
      narrative: "Alineación aliada: crédito, prestigio y un lugar en el tablero de 1945.",
      effects: { prestige: 14, economy: -4, forces: -4, people: -3, image: 12 },
      flags: ["wwii_allies", "un_active", "align_us"],
      ideology: { washington: 1 },
      souvenirs: ["pin_eeuu"],
      log: "Ruptura con el Eje; llega el crédito aliado.",
    },
  },
  {
    id: "golpe_1976",
    speaker: "Almirante en retiro",
    role: "Junta",
    title: "El Proceso",
    text: "Tres armas, un comunicado y la palabra aniquilar. Prometen orden y un Mundial. El precio es una noche que no termina.",
    art: "/art/dictatorship.jpg",
    kind: "historia",
    eras: ["dictadura"],
    minYear: 1976,
    maxYear: 1978,
    once: true,
    priority: 100,
    yearsAdvance: 1,
    left: {
      label: "Ceder el gobierno a la Junta",
      narrative: "El cuartel toma la Casa. La imagen exterior se quiebra de un modo que no se repara.",
      effects: { forces: 16, people: -18, prestige: -14, corruption: 10, economy: -6, image: -40 },
      flags: ["dictatorship_1976"],
      dictatorship: true,
      ideology: { militar: 2 },
      followUp: "desaparecidos",
      log: "Golpe de 1976: nace el Proceso.",
    },
    right: {
      label: "Llamar a la resistencia civil",
      narrative: "Intento de sostener la legalidad. El cuartel igual avanza; queda un relato.",
      effects: { people: 8, forces: -16, prestige: 6, economy: -8, image: 6 },
      flags: ["resisted_1976"],
      ideology: { rights: 2 },
      log: "Resistencia civil; el golpe igual avanza.",
    },
  },
  {
    id: "desaparecidos",
    speaker: "Abogada de familiares",
    role: "Derechos humanos",
    title: "Las Madres en la Plaza",
    text: "Pañuelos blancos, listas, un silencio oficial. El Ministerio pide no hacer caso a una campaña antiargentina. La historia va a preguntar qué hiciste con los papeles.",
    art: "/art/dictatorship.jpg",
    kind: "historia",
    eras: ["dictadura"],
    once: true,
    priority: 95,
    requireFlags: ["dictatorship_1976"],
    yearsAdvance: 1,
    left: {
      label: "Abrir archivos y frenar el plan",
      narrative: "Gesto de verdad: el mundo mira mejor; el cuartel se enfurece.",
      effects: { prestige: 14, people: 8, forces: -16, corruption: -6, image: 12 },
      flags: ["human_rights"],
      ideology: { rights: 2 },
      log: "Se intenta frenar el plan clandestino.",
    },
    right: {
      label: "Negar y profundizar",
      narrative: "El mundo se aparta. La imagen del país se hunde.",
      effects: { forces: 8, prestige: -16, people: -12, corruption: 12, image: -20 },
      flags: ["denied_crimes"],
      dictatorship: true,
      ideology: { militar: 1 },
      log: "Negacionismo de Estado; el mundo se aparta.",
    },
  },
  {
    id: "mundial_78",
    speaker: "Jefe de prensa",
    role: "Imagen",
    title: "Un mundial para no mirar",
    text: "La pelota tapa las cárceles, dicen los diarios del régimen. Invertir en estadios es prestigio barato o una vergüenza cara.",
    art: "/art/dictatorship.jpg",
    kind: "historia",
    eras: ["dictadura"],
    minYear: 1978,
    maxYear: 1979,
    once: true,
    priority: 70,
    yearsAdvance: 1,
    left: {
      label: "Hacer del Mundial una fiesta",
      narrative: "Tregua futbolera: ánimo corto, gasto y una foto que la FIFA recuerda.",
      effects: { people: 10, prestige: 6, economy: -10, corruption: 6, inflation: 4 },
      flags: ["worldcup_embrace"],
      log: "Mundial 78: la fiesta tapa el horror.",
    },
    right: {
      label: "Recortar y no celebrar",
      narrative: "Ahorra caja; la plaza lo lee como desprecio.",
      effects: { prestige: -4, economy: 6, people: -8, forces: -4 },
      log: "Se baja el perfil del Mundial.",
    },
  },
  {
    id: "malvinas",
    speaker: "Almirante de la flota",
    role: "Armada",
    title: "Causa Malvinas",
    text: "Abril de 1982. Un desembarco incruento para unir al país. Londres no es un diario de la tarde. Los pibes de conscripto no eligieron el archipiélago.",
    art: "/art/malvinas.jpg",
    kind: "historia",
    eras: ["dictadura"],
    minYear: 1982,
    maxYear: 1983,
    once: true,
    priority: 96,
    yearsAdvance: 1,
    left: {
      label: "Recuperar las islas por la fuerza",
      narrative: "Unidad corta y un riesgo existencial. Si las fuerzas están flojas, el mapa se parte.",
      effects: { people: 12, forces: 6, prestige: -6, economy: -12, image: -8 },
      flags: ["malvinas_war"],
      followUp: "malvinas_fin",
      ideology: { militar: 2 },
      log: "Desembarco en Malvinas.",
    },
    right: {
      label: "Negociación larga con Londres",
      narrative: "Evita la guerra; la causa sigue abierta y la plaza se enfría.",
      effects: { prestige: 6, people: -10, forces: -8, economy: 4, image: 6 },
      flags: ["malvinas_talks"],
      ideology: { rights: 1 },
      log: "Se evita la guerra; la causa sigue abierta.",
    },
  },
  {
    id: "malvinas_fin",
    speaker: "Oficial conscripto",
    role: "Infantería",
    title: "El invierno del Atlántico",
    text: "Harrier, hundimientos, frío. El Estado Mayor pide más tiempo; las madres piden a sus hijos.",
    art: "/art/malvinas.jpg",
    kind: "historia",
    eras: ["dictadura"],
    once: true,
    priority: 100,
    requireFlags: ["malvinas_war"],
    yearsAdvance: 1,
    left: {
      label: "Ordenar la rendición",
      narrative: "Salva vidas y tumba el prestigio militar. El régimen se queda sin relato.",
      effects: { people: -8, forces: -14, prestige: -6, economy: -4, image: -4 },
      flags: ["malvinas_defeat"],
      log: "Rendición en Malvinas; cae el prestigio militar.",
    },
    right: {
      label: "Pedir más hombres y más invierno",
      narrative: "Dobla la apuesta. El costo humano y diplomático se multiplica.",
      effects: { forces: -12, people: -16, prestige: -12, economy: -10, image: -10 },
      flags: ["malvinas_defeat"],
      log: "La guerra se alarga y se pierde igual.",
    },
  },
  {
    id: "hiper_89",
    speaker: "Ministro de Economía",
    role: "Hacienda",
    title: "La hiper",
    text: "Los precios cambian entre el almacén y la esquina. El austral es papel. Un pacto con el mercado puede calmar; emitir, incendiar.",
    art: "/art/nineties.jpg",
    kind: "historia",
    eras: ["noventa"],
    minYear: 1989,
    maxYear: 1991,
    once: true,
    priority: 90,
    yearsAdvance: 1,
    left: {
      label: "Shock y pacto con el mercado",
      narrative: "Baja la inflación a costa del salario. Abre la puerta a la convertibilidad.",
      effects: { economy: 6, prestige: 6, people: -10, corruption: 6, inflation: -18, image: 6 },
      flags: ["hyper_shock"],
      ideology: { market: 2 },
      log: "Shock antiinflacionario; el salario sufre.",
    },
    right: {
      label: "Controlar precios y emitir",
      narrative: "Alivio de mostrador. El asesino silencioso se alimenta.",
      effects: { people: 6, economy: -12, prestige: -8, inflation: 16, image: -6 },
      flags: ["hyper_emit"],
      ideology: { market: -2 },
      log: "Más emisión: la hiper se come el sueldo.",
    },
  },
  {
    id: "convertibilidad",
    speaker: "Ministro del uno a uno",
    role: "Economía",
    title: "Convertibilidad",
    text: "Un peso, un dólar, por ley. La inflación se muere en una semana. También se muere el tipo de cambio como herramienta. Las privatizaciones vienen en el mismo maletín.",
    art: "/art/nineties.jpg",
    kind: "historia",
    eras: ["noventa"],
    minYear: 1991,
    maxYear: 1994,
    once: true,
    priority: 94,
    yearsAdvance: 2,
    left: {
      label: "Fijar 1 a 1 y privatizar",
      narrative: "Estabiliza precios y abre mercados. La corrupción viaja en el mismo avión.",
      effects: { economy: 10, prestige: 12, people: 6, corruption: 12, forces: -4, inflation: -28, image: 10 },
      flags: ["convertibility", "privatizations"],
      ideology: { market: 2, washington: 1 },
      log: "Convertibilidad y oleada de privatizaciones.",
    },
    right: {
      label: "Flotar y sostener empresas públicas",
      narrative: "Conserva herramientas; la inflación sigue viva y el crédito se encarece.",
      effects: { people: 4, economy: -8, prestige: -8, corruption: -4, inflation: 8, image: -4 },
      flags: ["no_convertibility"],
      ideology: { market: -1 },
      log: "Se rechaza el 1 a 1; la inflación sigue viva.",
    },
  },
  {
    id: "privatizaciones",
    speaker: "Banquero de New York",
    role: "Bancos",
    title: "Todo es vendible",
    text: "YPF, teléfonos, trenes, agua. Prometen eficiencia. Los amigos del poder ya tienen sociedades en islas. El ramal que para, no vuelve.",
    art: "/art/nineties.jpg",
    kind: "historia",
    eras: ["noventa"],
    minYear: 1992,
    maxYear: 1999,
    once: true,
    priority: 70,
    requireFlags: ["privatizations"],
    yearsAdvance: 2,
    left: {
      label: "Vender ya, con apuro",
      narrative: "Caja rápida, comisiones opacas, ramales que mueren.",
      effects: { economy: 6, prestige: 4, corruption: 14, people: -10, image: -4 },
      ideology: { market: 1 },
      log: "Privatizaciones exprés y comisiones opacas.",
    },
    right: {
      label: "Licitar con reglas duras",
      narrative: "Más lento, más limpio. Washington se impacienta un poco.",
      effects: { prestige: 8, corruption: -6, economy: 2, people: 4, image: 6 },
      ideology: { rights: 1 },
      log: "Privatizaciones más limpias, más lentas.",
    },
  },
  {
    id: "cohete",
    speaker: "Ingeniero de la CONAE",
    role: "Espacio",
    title: "Cohete al espacio",
    text: "Hay un misil que Washington llama Cóndor y un satélite que nosotros llamamos soberanía. Inversión cara, prestigio raro, y un memorándum sobre la mesa.",
    art: "/art/nineties.jpg",
    kind: "historia",
    eras: ["noventa", "dosmil"],
    minYear: 1985,
    maxYear: 2014,
    once: true,
    priority: 58,
    yearsAdvance: 2,
    left: {
      label: "Financiar el programa espacial",
      narrative: "Soberanía técnica. Enfurece a Washington y ilumina a la universidad.",
      effects: { prestige: 12, economy: -10, forces: 4, people: 6, image: 4 },
      flags: ["space_program", "education_push"],
      ideology: { brics: 1 },
      log: "Se apuesta al plan espacial propio.",
    },
    right: {
      label: "Cancelar y comprar afuera",
      narrative: "Washington aplaude. El cielo se alquila.",
      effects: { economy: 6, prestige: -8, forces: -4, image: 4 },
      flags: ["space_cancelled", "align_us"],
      ideology: { washington: 1, market: 1 },
      souvenirs: ["pin_eeuu"],
      log: "Se cancela el cohete; Washington aplaude.",
    },
  },
  {
    id: "corralito",
    speaker: "Cajero del barrio",
    role: "Banco",
    title: "Corralito",
    text: "Diciembre de 2001. El ministro limita los retiros. Las cacerolas ya están en la vereda. Cinco presidentes pueden caber en una semana.",
    art: "/art/crisis.jpg",
    kind: "historia",
    eras: ["dosmil"],
    minYear: 2001,
    maxYear: 2002,
    once: true,
    priority: 100,
    yearsAdvance: 1,
    left: {
      label: "Abrir los bancos y devaluar",
      narrative: "Revienta el 1 a 1. El pueblo respira; el prestigio financiero se hunde.",
      effects: { people: 6, economy: -12, prestige: -10, forces: -4, corruption: 4, inflation: 18, image: -8 },
      flags: ["corralito", "default_2001"],
      ideology: { market: -1 },
      log: "Se levanta el corralito; devaluación y default.",
    },
    right: {
      label: "Profundizar el cepo y pedir al FMI",
      narrative: "El Fondo pide ajuste. La plaza puede incendiarse antes de que llegue el giro.",
      effects: { prestige: -2, people: -16, economy: -8, corruption: 8, forces: 4, inflation: 6, image: -4 },
      flags: ["corralito", "default_2001", "imf"],
      ideology: { washington: 1 },
      log: "El corralito se endurece; estalla el 19 y 20.",
    },
  },
  {
    id: "retenciones",
    speaker: "Productor de soja",
    role: "Campo",
    title: "La 125",
    text: "El campo para las rutas. El gobierno habla de mesa para todos. Una mesa chica puede terminar en cacerolas de ambos lados.",
    art: "/art/mendoza.jpg",
    kind: "historia",
    eras: ["dosmil"],
    minYear: 2008,
    maxYear: 2011,
    once: true,
    priority: 72,
    yearsAdvance: 1,
    left: {
      label: "Subir retenciones",
      narrative: "Caja fiscal y grieta. El campo se planta.",
      effects: { economy: 8, people: 5, prestige: -4, forces: -4, image: -2 },
      flags: ["retenciones"],
      ideology: { market: -1 },
      log: "Retenciones altas; el campo se planta.",
    },
    right: {
      label: "Bajar y pactar con la mesa de enlace",
      narrative: "Calma al agro, afloja la caja. Abre mercados de granos.",
      effects: { economy: -6, people: -5, prestige: 6, corruption: 4, image: 4 },
      ideology: { market: 1 },
      log: "Pacto con el campo; cae la caja fiscal.",
    },
  },
  {
    id: "ley_identidad",
    speaker: "Activista de la diversidad",
    role: "Sociedad civil",
    title: "Ley de Identidad de Género",
    text: "El DNI como se habita, no como se nació. La Iglesia pide una consulta; los organismos internacionales, una ley.",
    art: "/art/rights.jpg",
    kind: "historia",
    eras: ["dosmil", "dieciocho"],
    minYear: 2010,
    maxYear: 2016,
    once: true,
    priority: 74,
    yearsAdvance: 1,
    left: {
      label: "Sancionar la ley trans",
      narrative: "Vanguardia de derechos. Prestigio internacional; roce con las fuerzas y el púlpito.",
      effects: { people: 8, prestige: 12, forces: -6, image: 10 },
      flags: ["gender_law"],
      ideology: { rights: 2 },
      log: "Ley de Identidad de Género.",
    },
    right: {
      label: "Diferir y abrir debate",
      narrative: "Calma a un tercio; el otro no olvida. El mundo anota la postergación.",
      effects: { forces: 4, people: -8, prestige: -8, image: -8 },
      log: "Se frena la ley de identidad.",
    },
  },
  {
    id: "aborto",
    speaker: "Médica de un hospital público",
    role: "Salud",
    title: "La marea verde",
    text: "Pañuelos en las escalinatas. La Iglesia, en la otra vereda. Legalizar es un cisma cultural; no hacerlo, uno sanitario.",
    art: "/art/rights.jpg",
    kind: "historia",
    eras: ["dieciocho"],
    minYear: 2018,
    maxYear: 2021,
    once: true,
    priority: 88,
    yearsAdvance: 1,
    left: {
      label: "Legalizar el aborto",
      narrative: "Agenda feminista y prestigio de derechos. Parte al país en dos.",
      effects: { people: 6, prestige: 10, forces: -8, image: 8 },
      flags: ["abortion_law", "health_plan"],
      ideology: { rights: 2 },
      log: "Interrupción legal del embarazo.",
    },
    right: {
      label: "Mantener la penalización",
      narrative: "La Iglesia y una parte de las fuerzas respiran; la marea no se va.",
      effects: { forces: 6, people: -6, prestige: -8, image: -6 },
      flags: ["abortion_blocked"],
      log: "El aborto sigue penalizado.",
    },
  },
  {
    id: "ni_una_menos",
    speaker: "Colectivo feminista",
    role: "Calle",
    title: "Ni una menos",
    text: "Una marcha que no pide permiso. Emergencia en violencia, presupuesto o un discurso. El Ministerio de Seguridad mira el reloj.",
    art: "/art/rights.jpg",
    kind: "historia",
    eras: ["dieciocho", "dosmil"],
    minYear: 2015,
    maxYear: 2024,
    once: true,
    priority: 64,
    yearsAdvance: 1,
    left: {
      label: "Emergencia y presupuesto",
      narrative: "Política de género con partidas. Suma plaza y diplomas; resta caja.",
      effects: { people: 10, prestige: 8, economy: -4, forces: -4, image: 6 },
      flags: ["niunamenos", "health_plan"],
      ideology: { rights: 2 },
      log: "Política de género con presupuesto.",
    },
    right: {
      label: "Discurso y poco más",
      narrative: "La marea lee desprecio. El prestigio cultural se esfuma.",
      effects: { people: -8, prestige: -6, forces: 4, image: -4 },
      log: "Se subestima la marea feminista.",
    },
  },
  {
    id: "papa_argentino",
    speaker: "Nuncio apostólico",
    role: "Santa Sede",
    title: "El Papa es argentino",
    text: "Un cardenal de Flores aparece en el balcón de San Pedro. El país se detiene. Podés abrazar la mediación vaticana o marcar distancia laica.",
    art: "/art/vatican.jpg",
    kind: "diplomacia",
    eras: ["dosmil", "dieciocho"],
    minYear: 2013,
    maxYear: 2026,
    once: true,
    priority: 80,
    yearsAdvance: 1,
    left: {
      label: "Abrazar la mediación papal",
      narrative: "Prestigio moral y un souvenir de la Santa Sede. Washington y Moscú se ponen celosos.",
      effects: { people: 10, prestige: 10, image: 8, forces: 2 },
      flags: ["pope_argentine"],
      souvenirs: ["rosario_vaticano"],
      log: "El gobierno se sube al papa argentino.",
    },
    right: {
      label: "Distancia laica",
      narrative: "El Estado marca autonomía. Una parte de la plaza se enfría.",
      effects: { prestige: 4, people: -6, forces: -3, image: 2 },
      log: "El Estado marca distancia con la Iglesia.",
    },
  },
  {
    id: "ucrania",
    speaker: "Canciller",
    role: "Palacio San Martín",
    title: "Rusia, Ucrania, Washington",
    text: "Tres teléfonos. Uno pide granos y no condenar. Otro, armas y FMI. El tercero, mediación. En un mundo partido, abrazar a los tres es una fantasía.",
    art: "/art/diplomacy.jpg",
    kind: "diplomacia",
    eras: ["dieciocho"],
    minYear: 2022,
    maxYear: 2026,
    once: true,
    priority: 86,
    yearsAdvance: 1,
    left: {
      label: "Ayuda humanitaria y condena a Moscú",
      narrative: "Abre mercados occidentales y puede valer una Orden de la Libertad. Enfurece a Moscú.",
      effects: { prestige: 10, image: 10, economy: -4, people: -4, forces: 2 },
      flags: ["ukraine_aid", "align_us"],
      ideology: { washington: 2 },
      souvenirs: ["pin_eeuu"],
      log: "Condena a Rusia y ayuda a Ucrania.",
    },
    right: {
      label: "Neutralidad y granos a todos",
      narrative: "Multipolaridad: caja de commodities, riesgo de cierre de crédito occidental.",
      effects: { economy: 6, prestige: -6, image: -8, people: 4 },
      flags: ["align_brics"],
      ideology: { brics: 2 },
      marketClosed: true,
      log: "Neutralidad comercial ante la guerra.",
    },
  },
  {
    id: "turismo",
    speaker: "Ministra de Turismo",
    role: "Gabinete",
    title: "El país como postal",
    text: "Cataratas, glaciares, un cambio favorable. Abrir el cielo suma dólares e imagen. Un default o una dictadura los espanta a todos.",
    art: "/art/patagonia.jpg",
    kind: "historia",
    eras: ["noventa", "dosmil", "dieciocho"],
    minYear: 1994,
    once: true,
    priority: 48,
    yearsAdvance: 1,
    left: {
      label: "Plan nacional de turismo",
      narrative: "Imagen y caja si el país no está cerrado. Inflación alta lo licúa.",
      effects: { economy: 6, image: 8, people: 4, prestige: 4, inflation: 2 },
      flags: ["tourism"],
      log: "Plan nacional de turismo.",
    },
    right: {
      label: "Dejarlo al mercado hotelero",
      narrative: "Sin política, el turismo queda en recovas de siempre.",
      effects: { economy: 2, image: -2, prestige: -2 },
      ideology: { market: 1 },
      log: "Turismo sin política de Estado.",
    },
  },
  {
    id: "mundial_moderno",
    speaker: "Técnico de la selección",
    role: "Deporte",
    title: "Un mundial, una tregua",
    text: "La pelota para el país. Invertir en la fiesta da popularidad barata. Ignorarla es de estadista… o de suicida.",
    art: "/art/rights.jpg",
    kind: "flavor",
    eras: ["dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1978,
    once: true,
    priority: 50,
    yearsAdvance: 1,
    left: {
      label: "Abrazar la fiesta",
      narrative: "Tregua civil. Puede abrir el Living Football Award si el ánimo acompaña.",
      effects: { people: 12, economy: -4, prestige: 5, image: 4 },
      flags: ["worldcup_embrace"],
      log: "El gobierno se sube a la selección.",
    },
    right: {
      label: "Gobernar como si no hubiera pelota",
      narrative: "Gesto de sobriedad. La plaza no entiende.",
      effects: { people: -6, prestige: 2, economy: 2 },
      log: "Se ignora el Mundial.",
    },
  },
  {
    id: "onu_foro",
    speaker: "Embajadora en ONU",
    role: "Multilateral",
    title: "El atril de mármol",
    text: "Te toca el discurso de septiembre. Podés denunciar el orden financiero o pedir misiones de paz. Cada frase se traduce a crédito.",
    art: "/art/diplomacy.jpg",
    kind: "diplomacia",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1945,
    once: true,
    priority: 52,
    yearsAdvance: 1,
    left: {
      label: "Agenda de paz y descolonización",
      narrative: "Suma liderazgo global. Malvinas entra en el párrafo; Washington bosteza.",
      effects: { prestige: 8, image: 8, people: 4, economy: -2 },
      flags: ["un_active"],
      souvenirs: ["mate_sur"],
      log: "Discurso de paz en la ONU.",
    },
    right: {
      label: "Pedir crédito y alinear votos",
      narrative: "Abre mercado si el prestigio aguanta. Parece un lobby, no un país.",
      effects: { economy: 6, prestige: -4, image: 4, inflation: 4 },
      flags: ["align_us"],
      ideology: { washington: 1, market: 1 },
      souvenirs: ["pin_eeuu"],
      log: "La ONU se usa como vidriera de crédito.",
    },
  },
  {
    id: "visita_italia",
    speaker: "Presidente del Consiglio",
    role: "Visita",
    title: "Roma en la Rosada",
    text: "Una visita de Estado: inmigración, empresas y un sótano de vinos. El obsequio se espera de los dos lados.",
    art: "/art/diplomacy.jpg",
    kind: "diplomacia",
    eras: ["independencia", "noventa", "dosmil", "dieciocho"],
    minYear: 1880,
    once: true,
    priority: 44,
    yearsAdvance: 1,
    left: {
      label: "Afianzar lazos y firmar comercio",
      narrative: "Italia retribuye con vinos y un souvenir. Abre mercado europeo.",
      effects: { prestige: 6, image: 6, economy: 4, people: 3 },
      souvenirs: ["vino_italia"],
      flags: ["italy_ties"],
      log: "Cumbre con Italia y obsequio de vinos.",
    },
    right: {
      label: "Agenda corta, foto y nada más",
      narrative: "Ahorra compromisos. Roma se siente despreciada.",
      effects: { prestige: -4, image: -4, people: -2 },
      log: "Visita italiana de trámite.",
    },
  },
  {
    id: "visita_brasil",
    speaker: "Itamaraty",
    role: "Visita",
    title: "El vecino mayor",
    text: "Brasil ofrece energía, café y una silla en el Mercosur que a veces pesa como yugo.",
    art: "/art/diplomacy.jpg",
    kind: "diplomacia",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1822,
    once: true,
    priority: 42,
    yearsAdvance: 1,
    left: {
      label: "Cumbre y presente de Estado",
      narrative: "Café, comercio y un gesto amazónico. Suma imagen regional.",
      effects: { prestige: 5, image: 5, economy: 4 },
      souvenirs: ["cafe_brasil"],
      flags: ["brazil_ties"],
      log: "Cumbre con Brasil.",
    },
    right: {
      label: "Marcar distancia soberana",
      narrative: "Evita tutelas. El Mercosur se enfría.",
      effects: { prestige: -4, economy: -3, image: -3, people: 3 },
      log: "Distancia con Brasilia.",
    },
  },
  {
    id: "beagle",
    speaker: "Canciller chileno",
    role: "Límites",
    title: "El Beagle o los hielos",
    text: "Un canal, unas islas, un mapa que no coincide. La guerra con el vecino es popular una semana. El Papa ofrece mediación.",
    art: "/art/ushuaia.jpg",
    kind: "diplomacia",
    eras: ["independencia", "dictadura"],
    minYear: 1870,
    maxYear: 1985,
    once: true,
    priority: 66,
    yearsAdvance: 1,
    left: {
      label: "Aceptar mediación papal",
      narrative: "Paz con Santiago y un presente de cobre. Puede abrir el Nobel de la Paz.",
      effects: { prestige: 10, forces: -4, people: -3, image: 10 },
      flags: ["beagle_peace"],
      souvenirs: ["cobre_chile", "rosario_vaticano"],
      ideology: { rights: 1 },
      log: "Mediación papal con Chile.",
    },
    right: {
      label: "Movilizar al sur",
      narrative: "Tambores. Si las fuerzas están flojas, el riesgo de invasión deja de ser metafórico.",
      effects: { forces: 8, prestige: -8, economy: -8, people: 4, image: -10 },
      flags: ["chile_tension"],
      ideology: { militar: 1 },
      log: "Tensión bélica con Chile.",
    },
  },
  {
    id: "ushuaia_tech",
    speaker: "Gobernadora de Tierra del Fuego",
    role: "Provincia",
    title: "Polo tecnológico en Ushuaia",
    text: "En el fin del mundo piden fibra, exenciones y un satélite que mire el canal. Es caro. También es una foto de siglo XXI.",
    art: "/art/ushuaia.jpg",
    kind: "provincia",
    eras: ["noventa", "dosmil", "dieciocho"],
    minYear: 1995,
    once: true,
    priority: 46,
    yearsAdvance: 1,
    left: {
      label: "Financiar el polo austral",
      narrative: "Desarrollo de frontera: prestigio científico, gasto real.",
      effects: { prestige: 8, economy: -6, people: 5, image: 6 },
      flags: ["ushuaia_tech", "education_push"],
      souvenirs: ["mate_sur"],
      log: "Polo tecnológico en Ushuaia.",
    },
    right: {
      label: "Dejarlo a ensambladoras",
      narrative: "Tierra del Fuego sigue siendo aduana, no laboratorio.",
      effects: { economy: 3, prestige: -4, people: -4 },
      ideology: { market: 1 },
      log: "Ushuaia queda en manos de la ensambladora.",
    },
  },
  {
    id: "patagonia_tierras",
    speaker: "Escribano de Río Negro",
    role: "Provincia",
    title: "Venta de tierras en Patagonia",
    text: "Un fondo pide leguas frente al lago. Dicen turismo. Dicen soberanía al revés. El mapa no se discute en un country.",
    art: "/art/patagonia.jpg",
    kind: "provincia",
    eras: ["noventa", "dosmil", "dieciocho"],
    minYear: 1990,
    once: true,
    priority: 47,
    yearsAdvance: 1,
    left: {
      label: "Frenar la venta y regular",
      narrative: "Soberanía territorial. Enfurece al capital y suma plaza nacionalista.",
      effects: { people: 8, prestige: 6, economy: -6, image: 4, corruption: -4 },
      flags: ["patagonia_guard"],
      log: "Se frena la venta de tierras patagónicas.",
    },
    right: {
      label: "Autorizar con canon",
      narrative: "Dólares de corto plazo, rumor de país en oferta.",
      effects: { economy: 8, corruption: 8, people: -8, prestige: -6, image: -6 },
      ideology: { market: 1 },
      log: "Tierras patagónicas a fondos extranjeros.",
    },
  },
  {
    id: "jujuy_narco",
    speaker: "Fiscal de frontera",
    role: "Provincia",
    title: "La quebrada tomada",
    text: "Ruta 34, pasos no habilitados, un ministerio que no da abasto. Mano militar o inteligencia y jueces. Las dos duelen.",
    art: "/art/jujuy.jpg",
    kind: "provincia",
    eras: ["dosmil", "dieciocho", "noventa"],
    minYear: 1995,
    once: true,
    priority: 49,
    yearsAdvance: 1,
    left: {
      label: "Emergencia con fuerzas federales",
      narrative: "Orden visible. Si las fuerzas están rotas, es teatro.",
      effects: { forces: 8, people: 3, corruption: 4, economy: -3, image: 2 },
      ideology: { militar: 1 },
      log: "Emergencia de seguridad en Jujuy.",
    },
    right: {
      label: "Jueces, GML y pasos",
      narrative: "Más lento, más limpio. El narco tiene tiempo.",
      effects: { corruption: -8, prestige: 6, people: -3, economy: -5, image: 4 },
      ideology: { rights: 1 },
      log: "Ataque a la plata del narco en la frontera norte.",
    },
  },
  {
    id: "mendoza_vino",
    speaker: "Viticultora de Luján",
    role: "Provincia",
    title: "La cosecha y la falla",
    text: "Mendoza ofrece denominación de origen y una falla sísmica que no avisa. Invertir en viñas es imagen; ignorar las normas, una masacre futura.",
    art: "/art/mendoza.jpg",
    kind: "provincia",
    eras: ["independencia", "noventa", "dosmil", "dieciocho"],
    minYear: 1885,
    once: true,
    priority: 45,
    yearsAdvance: 1,
    left: {
      label: "Impulsar la vitivinicultura y normas sísmicas",
      narrative: "Marca país y un poco de prevención. La caja lo siente.",
      effects: { economy: 6, image: 6, prestige: 4, people: 4, inflation: 1 },
      flags: ["mendoza_wine"],
      log: "Plan vitivinícola y normas sísmicas en Mendoza.",
    },
    right: {
      label: "Dejarlo al mercado y a la Virgen",
      narrative: "Ahorra. El próximo temblor no negocia.",
      effects: { economy: 3, people: -4, image: -3, prestige: -2 },
      ideology: { market: 1 },
      log: "Mendoza queda a merced del mercado.",
    },
  },
  {
    id: "inundacion",
    speaker: "Intendente del litoral",
    role: "Emergencia",
    title: "El río se come el pueblo",
    text: "El Paraná no pide permiso. Techos bajo el agua, escuelas-isla, un puente que ya no está. No hay decisión buena: hay menos mala.",
    art: "/art/flood.jpg",
    kind: "desastre",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1850,
    priority: 40,
    weight: 0.7,
    yearsAdvance: 1,
    left: {
      label: "Ayuda directa y obras",
      narrative: "Todo costo, nada de ganancia. El pueblo lo nota apenas.",
      effects: { people: -2, economy: -10, corruption: 3, inflation: 3, prestige: -2 },
      log: "Inundación: ayuda de emergencia.",
    },
    right: {
      label: "Declarar emergencia y poco más",
      narrative: "Peor. El litoral no olvida, y la economía igual se moja.",
      effects: { people: -12, economy: -6, prestige: -4, image: -4 },
      log: "Inundación sin presupuesto.",
    },
  },
  {
    id: "terremoto",
    speaker: "Gobernador de Cuyo",
    role: "Emergencia",
    title: "La tierra no avisa",
    text: "Un sismo parte una iglesia, un hospital, una noche. Los escombros no distinguen bandera. El Estado llega tarde o no llega.",
    art: "/art/quake.jpg",
    kind: "desastre",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1861,
    priority: 40,
    weight: 0.65,
    yearsAdvance: 1,
    left: {
      label: "Cadenas de rescate y reconstrucción",
      narrative: "Gasto puro. Mitiga muertes; no hay foto que alcance.",
      effects: { people: -4, economy: -12, forces: -4, inflation: 4, prestige: -2 },
      log: "Terremoto: plan de reconstrucción.",
    },
    right: {
      label: "Dejarlo a las provincias",
      narrative: "Peor aún. La imagen del país se llena de polvo.",
      effects: { people: -14, economy: -7, image: -8, prestige: -6 },
      log: "Terremoto sin Estado nacional.",
    },
  },
  {
    id: "escandalo_fiscal",
    speaker: "Fiscal federal",
    role: "Comodoro Py",
    title: "El abogado con la valija",
    text: "Un fiscal tiene pruebas. Facturas, chats, un chofer. Tres caminos: sicarios, una campaña de lodo, o el juicio. El primero puede ser el último.",
    art: "/art/scandal.jpg",
    kind: "escandalo",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1890,
    minStats: { corruption: 48 },
    priority: 82,
    weight: 1.3,
    yearsAdvance: 1,
    left: {
      label: "Campaña de difamación",
      narrative: "Ensucia al fiscal. Cuesta prestigio y plata; no es un homicidio.",
      effects: { prestige: -10, people: -8, corruption: 6, influence: 4, money: -900_000, image: -6 },
      log: "Campaña sucia contra el fiscal.",
    },
    right: {
      label: "Ir a juicio",
      narrative: "Cincuenta y cincuenta. La verdad, o la banda en el palacio de tribunales.",
      effects: { prestige: 4, people: 2, corruption: -6 },
      flags: ["stood_trial"],
      followUp: "juicio_veredicto",
      log: "El mandatario se somete a juicio.",
    },
  },
  {
    id: "escandalo_sicario",
    speaker: "Hombre de la side",
    role: "Sombras",
    title: "Una solución final",
    text: "Alguien ofrece un accidente de tránsito. Si sale mal —y suele salir mal— no hay banda ni exilio que alcance.",
    art: "/art/scandal.jpg",
    kind: "escandalo",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1890,
    minStats: { corruption: 62 },
    priority: 70,
    weight: 0.8,
    yearsAdvance: 1,
    left: {
      label: "Rechazar y desarmar la red",
      narrative: "Te sacás las manos de encima. El fiscal sigue vivo y la causa también.",
      effects: { corruption: -8, prestige: 4, people: 4, forces: -4, image: 4 },
      log: "Se rechaza el crimen de Estado.",
    },
    right: {
      label: "Dar luz verde a los sicarios",
      narrative: "Altísimo riesgo de derrumbe. Si el crimen sale a la luz, se acaba el gobierno.",
      effects: { corruption: 12, people: -10, prestige: -8, image: -12 },
      riskGameOver: 0.62,
      riskReason: "crime",
      flags: ["sicarios"],
      ideology: { militar: 1 },
      log: "Se ordena un crimen de Estado.",
    },
  },
  {
    id: "juicio_veredicto",
    speaker: "Tribunal oral",
    role: "Justicia",
    title: "El veredicto",
    text: "La sala está llena. El fiscal lee. No hay tercera vía entre la absolución política y la destitución.",
    art: "/art/scandal.jpg",
    kind: "escandalo",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    once: true,
    priority: 100,
    requireFlags: ["stood_trial"],
    yearsAdvance: 1,
    left: {
      label: "Aceptar el fallo",
      narrative: "Si el prestigio y la imagen sostienen, hay chance de zafar. Si no, el tribunal te destituye.",
      effects: { prestige: 2, people: 2 },
      riskGameOver: 0.42,
      riskReason: "trial",
      log: "Se espera el fallo del tribunal.",
    },
    right: {
      label: "Fugarse del recinto",
      narrative: "Peor. Parece admisión. El riesgo de caída es aún más alto.",
      effects: { prestige: -12, people: -10, image: -10, forces: -6 },
      riskGameOver: 0.7,
      riskReason: "trial",
      log: "El mandatario huye del tribunal.",
    },
  },
  {
    id: "revolta",
    speaker: "Columna de la plaza",
    role: "Calle",
    title: "La revuelta",
    text: "Ya no son cacerolas: son columnas. Si la felicidad no pega un salto ahora, la revolución no pide permiso.",
    art: "/art/crisis.jpg",
    kind: "revolta",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    priority: 100,
    yearsAdvance: 0,
    left: {
      label: "Reparto de emergencia y diálogo",
      narrative: "Última chance. Cuesta caja e inflación; puede evitar el final.",
      effects: { people: 14, economy: -10, inflation: 8, corruption: 4, forces: -4 },
      flags: ["revolt_handled"],
      log: "Se intenta desactivar la revuelta con emergencia social.",
    },
    right: {
      label: "Gendarmería a la plaza",
      narrative: "Fuego. Si falla, es revolución. Si pega, es una herida que no cierra.",
      effects: { forces: 8, people: -16, prestige: -8, image: -10 },
      flags: ["revolt_repressed"],
      ideology: { militar: 1 },
      log: "Represión de la revuelta.",
    },
  },
  {
    id: "inseguridad",
    speaker: "Jefa de policía",
    role: "Seguridad",
    title: "La ciudad tomada",
    text: "Con las fuerzas en mínima, la violencia urbana deja de ser un gráfico. Piden gendarmería o un plan social que ya no hay con qué pagar.",
    art: "/art/crisis.jpg",
    kind: "flavor",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    maxStats: { forces: 24 },
    priority: 78,
    weight: 1.2,
    yearsAdvance: 1,
    left: {
      label: "Toque de queda y tropas",
      narrative: "Orden corto. El pueblo se asusta; el cuartel sonríe.",
      effects: { forces: 10, people: -8, image: -4, prestige: -2 },
      ideology: { militar: 1 },
      log: "Toque de queda por inseguridad.",
    },
    right: {
      label: "Plan de barrios y trabajo",
      narrative: "Más lento. Si no hay caja, es un discurso.",
      effects: { people: 6, economy: -8, forces: 2, inflation: 3 },
      log: "Plan social contra la inseguridad.",
    },
  },
  {
    id: "invasion",
    speaker: "Agregado militar",
    role: "Defensa",
    title: "Presión en la frontera",
    text: "Con el ejército desleído y el prestigio en el piso, una potencia prueba hechos. Un guardacostas que no sale, un mapa que se mueve.",
    art: "/art/malvinas.jpg",
    kind: "flavor",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    maxStats: { forces: 18, prestige: 30 },
    priority: 85,
    weight: 1.1,
    yearsAdvance: 1,
    left: {
      label: "Protesta diplomática y alianzas",
      narrative: "Si la imagen aún vale, hay quien atienda. Si no, es papel.",
      effects: { prestige: 6, image: 4, forces: -4, people: -4 },
      riskGameOver: 0.28,
      riskReason: "invasion",
      log: "Protesta diplomática ante una presión fronteriza.",
    },
    right: {
      label: "Movilizar lo que queda",
      narrative: "Último cartucho militar. Puede ser disuasión o el final del mapa.",
      effects: { forces: 8, economy: -8, people: -6, prestige: -4 },
      riskGameOver: 0.34,
      riskReason: "invasion",
      ideology: { militar: 1 },
      log: "Movilización ante presión extranjera.",
    },
  },
  {
    id: "prestamo_baring",
    speaker: "Casa Baring",
    role: "Crédito",
    title: "Oro a crédito",
    text: "Un empréstito ofrece alivio. Pedirlo alimenta al asesino silencioso. Si el prestigio es bajo o el mercado está cerrado, ni siquiera te atienden.",
    art: "/art/nineties.jpg",
    kind: "flavor",
    eras: ["independencia", "noventa", "dosmil", "dieciocho"],
    minYear: 1824,
    priority: 36,
    weight: 0.9,
    yearsAdvance: 1,
    left: {
      label: "Tomar el crédito",
      narrative: "Caja ahora, inflación después. El mercado cobra en imagen.",
      effects: { economy: 8, prestige: 2, inflation: 14, corruption: 4, people: -2, image: -2, money: 2_400_000 },
      flags: ["debt"],
      log: "Nuevo empréstito externo.",
    },
    right: {
      label: "Vivir con lo nuestro",
      narrative: "Ajuste interno. Duro, soberano, impopular.",
      effects: { prestige: -2, economy: -6, people: 3, inflation: -2, corruption: -2 },
      log: "Se rechaza el crédito; hay ajuste interno.",
    },
  },
  {
    id: "educacion",
    speaker: "Maestra rural",
    role: "Educación",
    title: "La escuela o el cuartel",
    text: "Faltan maestros, edificios y un siglo de promesas. Un presupuesto serio se come otras partidas. El himno no alcanza.",
    art: "/art/independence.jpg",
    kind: "flavor",
    eras: ["independencia", "dictadura", "noventa", "dosmil", "dieciocho"],
    minYear: 1884,
    priority: 34,
    weight: 0.85,
    yearsAdvance: 1,
    left: {
      label: "Ley de financiamiento educativo",
      narrative: "Puede abrir un honoris causa. La caja lo siente.",
      effects: { people: 8, economy: -6, prestige: 6, inflation: 2 },
      flags: ["education_push"],
      ideology: { rights: 1 },
      log: "Inversión educativa.",
    },
    right: {
      label: "Dejarlo a las provincias",
      narrative: "Ahorra. La escuela queda a merced de cada gobernador.",
      effects: { economy: 4, people: -6, prestige: -3 },
      log: "La escuela queda a merced de cada gobernador.",
    },
  },
  {
    id: "polarizacion",
    speaker: "Consultor de imagen",
    role: "Gabinete",
    title: "La grieta",
    text: "La mitad del país no le cree a la otra. Podés gobernar para tu tercio o armar una mesa que nadie quiere.",
    art: "/art/rights.jpg",
    kind: "flavor",
    eras: ["dosmil", "dieciocho"],
    minYear: 2008,
    weight: 1.05,
    yearsAdvance: 1,
    left: {
      label: "Gobernar para los propios",
      narrative: "Animo de tribu, prestigio de país partido.",
      effects: { people: 5, prestige: -6, forces: 3, corruption: 4, image: -4 },
      log: "Se profundiza la grieta.",
    },
    right: {
      label: "Pacto transversal",
      narrative: "Estadista. Tu base se enoja.",
      effects: { prestige: 8, people: -4, corruption: -4, forces: -3, image: 6 },
      ideology: { rights: 1 },
      log: "Intento de pacto transversal.",
    },
  },
];

export const EVENT_MAP = Object.fromEntries(EVENTS.map((e) => [e.id, e]));
