import type { ShopItem } from "./types";

export const SHOP: ShopItem[] = [
  {
    id: "carruaje",
    name: "Carruaje de gala",
    blurb: "Lacas, caballos y un estribo que se ve desde la recova. No hay jets en 1816.",
    costARS: 280_000,
    costInfluence: 0,
    minYear: 1816,
    maxYear: 1925,
    luxury: true,
    effects: { prestige: 4, image: 2 },
    narrative: "Un lujo de época. Si el pueblo pasa hambre, la gazeta lo va a pintar como escándalo.",
  },
  {
    id: "estancia",
    name: "Estancia en la pampa",
    blurb: "Hacienda, ganado y un apellido que suena a campo.",
    costARS: 1_600_000,
    costInfluence: 0,
    minYear: 1816,
    luxury: false,
    effects: { economy: 3, prestige: 4, influence: 4 },
    narrative: "Patrimonio rural: suma abolengo y una caja chica ganadera.",
  },
  {
    id: "plata",
    name: "Vajilla de plata",
    blurb: "Un tren de vida visible, sin necesidad de hangar.",
    costARS: 160_000,
    costInfluence: 0,
    minYear: 1816,
    maxYear: 1950,
    luxury: true,
    effects: { prestige: 3, influence: 3 },
    narrative: "Brillo de salón. En años de carestía, parece una bofetada.",
  },
  {
    id: "gazeta",
    name: "Financiar gazetas",
    blurb: "Hojas sueltas, grabados y un retrato favorable en la esquina.",
    costARS: 210_000,
    costInfluence: 2,
    minYear: 1816,
    maxYear: 1935,
    luxury: false,
    effects: { people: 10, corruption: 4 },
    narrative: "Campaña de época: diarios y pasquines para intentar revertir una caída de popularidad.",
  },
  {
    id: "caudillos",
    name: "Sobornar caudillos",
    blurb: "Montoneras que de pronto encuentran razones para no marchar.",
    costARS: 420_000,
    costInfluence: 6,
    minYear: 1816,
    maxYear: 1885,
    luxury: false,
    effects: { forces: 10, corruption: 8, people: -4 },
    narrative: "Comprás lealtad armada. Baja el dinero; sube la tropa — y la mancha.",
  },
  {
    id: "jueces",
    name: "Comprar jueces",
    blurb: "Expedientes que se duermen. La corrupción visible baja; la real, no.",
    costARS: 980_000,
    costInfluence: 12,
    minYear: 1853,
    luxury: false,
    effects: { corruption: -12, forces: 4, prestige: -6 },
    narrative: "La causa se traspapela. Cuesta plata e influencia; el fuero respira.",
  },
  {
    id: "guardia",
    name: "Guardia de honor",
    blurb: "Hombres de confianza en la puerta. El cuartel lo nota.",
    costARS: 360_000,
    costInfluence: 4,
    minYear: 1816,
    luxury: false,
    effects: { forces: 10, people: -2 },
    narrative: "Más lealtad inmediata de las armas, a costa de una foto militarizada.",
  },
  {
    id: "banquete",
    name: "Banquete diplomático",
    blurb: "Vinos, toasts y un mapa doblado entre cubiertos.",
    costARS: 95_000,
    costInfluence: 2,
    minYear: 1816,
    luxury: false,
    effects: { prestige: 5, image: 4, money: 0 },
    narrative: "Cortesía de Estado: abre puertas y algún souvenir menor.",
    flags: ["hosted_banquet"],
  },
  {
    id: "mansion",
    name: "Mansión en Recoleta",
    blurb: "Mármol, palmeras y un hall para recibir embajadores.",
    costARS: 6_400_000,
    costInfluence: 0,
    minYear: 1853,
    luxury: true,
    effects: { prestige: 6, influence: 6 },
    narrative: "Si la pobreza es alta, los noticieros van a cruzar tu jardín con el índice de indigencia.",
  },
  {
    id: "diario",
    name: "Comprar un diario",
    blurb: "La tapa es tuya. La calle, a veces también.",
    costARS: 2_800_000,
    costInfluence: 6,
    minYear: 1890,
    maxYear: 2010,
    luxury: false,
    effects: { people: 9, prestige: 3, corruption: 6 },
    narrative: "Influencia mediática clásica: papel y tinta para enderezar una elección fea.",
  },
  {
    id: "radio_tv",
    name: "Cadena de radio y TV",
    blurb: "Un canal propio, un conductor amigo, un recuento piadoso.",
    costARS: 4_200_000,
    costInfluence: 8,
    minYear: 1951,
    maxYear: 2014,
    luxury: false,
    effects: { people: 12, corruption: 5, prestige: 2 },
    narrative: "Campaña clásica de diarios y televisión, útil antes de un comicio.",
  },
  {
    id: "yate",
    name: "Yate en el Tigre",
    blurb: "Cubierta de teca y fiestas que no salen en el Boletín Oficial.",
    costARS: 9_200_000,
    costInfluence: 0,
    minYear: 1962,
    luxury: true,
    effects: { people: 2, influence: 5, prestige: 3 },
    narrative: "Lujo náutico. Con el pueblo en crisis, es una tapa anunciada.",
  },
  {
    id: "jet",
    name: "Jet privado",
    blurb: "Despegás cuando querés. Los noticieros cuentan cada aterrizaje.",
    costARS: 22_000_000,
    costInfluence: 0,
    minYear: 1988,
    luxury: true,
    effects: { prestige: 6, influence: 5 },
    narrative: "No existía en 1816. Hoy existe, y el escándalo también.",
  },
  {
    id: "politicos",
    name: "Comprar bloques",
    blurb: "Bancadas que votan en fila. Sube la lealtad; baja el dinero.",
    costARS: 1_700_000,
    costInfluence: 10,
    minYear: 1853,
    luxury: false,
    effects: { forces: 6, people: -4, corruption: 8, influence: 6 },
    narrative: "Influencia legislativa comprada. El cuartel y el Congreso se alinean un rato.",
  },
  {
    id: "fundacion",
    name: "Fundación con tu nombre",
    blurb: "Hospitales, becas, una placa. Lava imagen, no siempre pecados.",
    costARS: 2_200_000,
    costInfluence: 0,
    minYear: 1920,
    luxury: false,
    effects: { people: 10, prestige: 6, corruption: -3 },
    flags: ["health_plan"],
    narrative: "Filantropía visible: sube la estima y puede abrir premios de desarrollo.",
  },
  {
    id: "bots",
    name: "Granja de bots y streamers",
    blurb: "Tendencias, cortes, un ejército que no vota pero grita.",
    costARS: 1_350_000,
    costInfluence: 4,
    minYear: 2012,
    luxury: false,
    effects: { people: 14, corruption: 6, prestige: -4 },
    narrative: "Campaña moderna: útil si la popularidad se cae antes de una votación.",
  },
  {
    id: "campana",
    name: "Campaña de urgencia",
    blurb: "Afiches, radios, asados. El pueblo te vuelve a mirar una semana.",
    costARS: 720_000,
    costInfluence: 3,
    minYear: 1916,
    maxYear: 2011,
    luxury: false,
    effects: { people: 12, corruption: 4 },
    narrative: "Gasto electoral clásico para intentar evitar un balotaje o una derrota.",
  },
  {
    id: "reforma",
    name: "Reforma constitucional",
    blurb: "Comprar el recinto para habilitar un tercer mandato.",
    costARS: 3_800_000,
    costInfluence: 22,
    minYear: 1853,
    minMandateYear: 4,
    luxury: false,
    effects: { corruption: 10, prestige: -6, people: -6 },
    flags: ["constitution_reformed"],
    narrative: "Habilita la re-reelección. El costo político es inmediato; el poder, no tanto.",
  },
];

export function availableShop(year: number, mandateYear: number, owned: string[]) {
  return SHOP.filter((item) => {
    if (owned.includes(item.id)) return false;
    if (year < item.minYear) return false;
    if (item.maxYear && year > item.maxYear) return false;
    if (item.minMandateYear && mandateYear < item.minMandateYear) return false;
    return true;
  }).slice(0, 12);
}
